import os
import sys
import pandas as pd
import re

sys.path.insert(0, r"D:\AFO_Codes")
sys.path.insert(0, r"D:\AFO_Codes\TreadMetrix")

from TreadMetrix.joint_power_computing import compute_angular_velocity, compute_joint_power
from resources.file_types.mot import MOT

def run_jp():
    ik_dir = r"Z:\AFO\Collected Data\P03-Processed\P03\P03\ik_results"
    id_dir = r"Z:\AFO\Collected Data\P03-Processed\P03\P03\id_results"
    power_dir = r"Z:\AFO\Collected Data\P03-Processed\P03\P03\joint_power"
    
    os.makedirs(power_dir, exist_ok=True)
    
    for side in ["Right", "Left"]:
        ik_side_dir = os.path.join(ik_dir, side)
        id_side_dir = os.path.join(id_dir, side)
        power_side_dir = os.path.join(power_dir, side)
        
        if not os.path.exists(ik_side_dir) or not os.path.exists(id_side_dir):
            continue
            
        os.makedirs(power_side_dir, exist_ok=True)
        
        ik_files = [f for f in os.listdir(ik_side_dir) if f.endswith(".mot")]
        for ik_file in ik_files:
            m = re.search(r"cycle(\d+)\.mot", ik_file)
            if not m:
                continue
            cycle_num = m.group(1)
            
            # The ID file generated by run_custom_id.py has the format: {trial_name}_{side}_cycle{cycle_num}.mot
            trial_name = "P03_Gait01"
            id_file = f"{trial_name}_{side}_cycle{cycle_num}.mot"
            
            ik_path = os.path.join(ik_side_dir, ik_file)
            id_path = os.path.join(id_side_dir, id_file)
            
            if not os.path.exists(id_path):
                print(f"ID file missing for {ik_file}: {id_path}")
                continue
            
            print(f"Computing joint power for side {side}, cycle {cycle_num}...")
            
            # Load DataFrames
            try:
                ik_mot = MOT.load_from_mot(ik_path)
                id_mot = MOT.load_from_mot(id_path)
            except Exception as e:
                print(f"Error loading MOT files for cycle {cycle_num}: {e}")
                continue
                
            try:
                angular_velocity = compute_angular_velocity(ik_mot.data, trial_name)
                joint_power = compute_joint_power(angular_velocity, id_mot.data, side)
                
                output_filename = f"{trial_name}_{side}_{cycle_num}.csv"
                output_file_path = os.path.join(power_side_dir, output_filename)
                
                joint_power.to_csv(output_file_path, index=False)
                print(f"Saved: {output_filename}")
            except Exception as e:
                print(f"Error computing joint power for cycle {cycle_num}: {e}")

if __name__ == '__main__':
    run_jp()
